### ISSUE TITLE
Consider encoding spaces as %20 instead of +

### ISSUE THREAD

**Issue by finnbear** [bww/urlencode#3]
Hi, thanks for making this useful tool! I noticed that it encodes spaces with the + character, which isn't compatible with SVG's encoded in data uri's (my use-case).

According to https://stackoverflow.com/a/40292770/3064544:

> It's better to always encode spaces as %20 rather than as +, even in the query part of a URL.

%20 is the default in at least one other tool: https://github.com/iossefy/urlenc (there is an opt-in option for +)

## Workaround

`urlenc enc | sed 's/+/%20/g'`

**Comment by bww** [comment]
Hi @finnbear, thanks for your suggestion.

URL encoding is currently done by the Go standard library function [`url.QueryEscape`](https://pkg.go.dev/net/url#QueryEscape), here: https://github.com/bww/urlencode/blob/master/cmd/urlenc/encode.go#L76

That function prefers `+` to `%20` and we inherit that preference. As `url.QueryEscape` doesn't support any options for how the encoding is done, in order to get the hex encoding for spaces, we'd have to either do a second pass to replace `+` with `%20` on the output of `QueryEscape` (yuck) or use some other implementation to do the encoding.

(The related function [`url.PathEscape`](https://pkg.go.dev/net/url#PathEscape) uses hex encoding for spaces but it also seems to pass through `+` as a literal, which would make that output incompatible with usage in a query string, which is really our primary use case, so it doesn't appear to be a suitable replacement.)

As such, as far as I'm aware, that means we'd have to find some third party implementation that will always encode spaces as `%20` without creating an ambiguity with `+` at the same time. If you have a suggestion for such an implementation, I'd take a look at it, but otherwise, I think this seems like too significant a change when, as you point out, it's easy enough to convert the `+` encoding via `sed` or something similar.

**Comment by finnbear** [comment]
Thanks for your response! I don't have a better implementation than replacing `+` with `%20` in the output of `url.QueryEscape`. For now, the README does say that this tool is for query strings not arbitrary [URL encoding](https://en.wikipedia.org/wiki/Percent-encoding) as the name would imply.
> A command line tool for manipulating URL-encoded **query strings**.
